//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusSystem.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public Booking()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int BookingId { get; set; }
        public Nullable<double> ActualFare { get; set; }
        public int NofSeats { get; set; }
        public int ScheduleId { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
        public virtual BusSchedule BusSchedule { get; set; }
    }
}
