//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusSystem.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingDetail
    {
        public int BookingId { get; set; }
        public int PassengerId { get; set; }
        public string SeatNo { get; set; }
    
        public virtual Booking Booking { get; set; }
        public virtual PassengerInfo PassengerInfo { get; set; }
    }
}
