//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusSystem.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusInfo
    {
        public BusInfo()
        {
            this.BusSchedules = new HashSet<BusSchedule>();
        }
    
        public int BusId { get; set; }
        public string BusName { get; set; }
        public int TotalSeats { get; set; }
        public int CategoryId { get; set; }
    
        public virtual ICollection<BusSchedule> BusSchedules { get; set; }
        public virtual CategoryInfo CategoryInfo { get; set; }
    }
}
