//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusSystem.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassengerInfo
    {
        public PassengerInfo()
        {
            this.BookingDetails = new HashSet<BookingDetail>();
        }
    
        public int PassengerId { get; set; }
        public string PassengerName { get; set; }
        public string Gender { get; set; }
        public int Age { get; set; }
        public long Contact { get; set; }
    
        public virtual ICollection<BookingDetail> BookingDetails { get; set; }
    }
}
